-- Auto-generated from the original src/data/products.js (53 items).
-- Run AFTER schema.sql. Safe to run once; re-running will duplicate rows.
insert into public.products (name, category, badge, img, status, sort_order) values
  ('Black Forest', 'Fresh Cream Cakes', null, null, 'active', 10),
  ('White Forest', 'Fresh Cream Cakes', null, null, 'active', 20),
  ('Chocolate Truffle', 'Fresh Cream Cakes', null, null, 'active', 30),
  ('Red Velvet', 'Fresh Cream Cakes', null, null, 'active', 40),
  ('Purple Velvet', 'Fresh Cream Cakes', null, null, 'active', 50),
  ('Pista Velvet', 'Fresh Cream Cakes', null, null, 'active', 60),
  ('Pista Truffle', 'Fresh Cream Cakes', null, null, 'active', 70),
  ('Butterscotch', 'Fresh Cream Cakes', null, null, 'active', 80),
  ('Blueberry', 'Fresh Cream Cakes', null, null, 'active', 90),
  ('Strawberry', 'Fresh Cream Cakes', null, null, 'active', 100),
  ('Pineapple', 'Fresh Cream Cakes', null, null, 'active', 110),
  ('Black Currant', 'Fresh Cream Cakes', null, null, 'active', 120),
  ('Choco Fantasy', 'Fresh Cream Cakes', null, null, 'active', 130),
  ('Mousse Cup', 'Fresh Cream Cakes', null, null, 'active', 140),
  ('Customized Birthday Cakes', 'Customized Cakes', null, null, 'active', 150),
  ('Theme Cakes', 'Customized Cakes', null, null, 'active', 160),
  ('Photo Cakes', 'Customized Cakes', null, null, 'active', 170),
  ('Anniversary Cakes', 'Customized Cakes', null, null, 'active', 180),
  ('Wedding Cakes', 'Customized Cakes', null, null, 'active', 190),
  ('Baby Shower Cakes', 'Customized Cakes', null, null, 'active', 200),
  ('Engagement Cakes', 'Customized Cakes', null, null, 'active', 210),
  ('Kids'' Character Cakes', 'Customized Cakes', null, null, 'active', 220),
  ('Number Cakes', 'Customized Cakes', null, null, 'active', 230),
  ('Alphabet Cakes', 'Customized Cakes', null, null, 'active', 240),
  ('Eggless Customized Cakes', 'Customized Cakes', 'On Request', null, 'active', 250),
  ('Normal Varkey', 'Ooty Special Bakery', null, null, 'active', 260),
  ('Ghee Varkey', 'Ooty Special Bakery', null, null, 'active', 270),
  ('Brown Sugar Varkey', 'Ooty Special Bakery', null, null, 'active', 280),
  ('Masala Varkey', 'Ooty Special Bakery', null, null, 'active', 290),
  ('Salt Cookies', 'Ooty Special Bakery', null, null, 'active', 300),
  ('Sweet Cookies', 'Ooty Special Bakery', null, null, 'active', 310),
  ('Peanut Cookies', 'Ooty Special Bakery', null, null, 'active', 320),
  ('Assorted Homemade Chocolates', 'Homemade Chocolates', null, null, 'active', 330),
  ('Brownies', 'Desserts', null, null, 'active', 340),
  ('Brownie with Ice Cream', 'Desserts', null, null, 'active', 350),
  ('Chocolate Lava Cake', 'Desserts', null, null, 'active', 360),
  ('Carrot Cake', 'Desserts', null, null, 'active', 370),
  ('Banana Cake', 'Desserts', null, null, 'active', 380),
  ('Swiss Roll', 'Desserts', null, null, 'active', 390),
  ('Mini Doughnuts', 'Desserts', null, null, 'active', 400),
  ('Rich Plum Cake', 'Desserts', null, null, 'active', 410),
  ('Seasonal Fresh Juices', 'Beverages', null, null, 'active', 420),
  ('Chocolate Milkshake', 'Beverages', null, null, 'active', 430),
  ('Strawberry Milkshake', 'Beverages', null, null, 'active', 440),
  ('Vanilla Milkshake', 'Beverages', null, null, 'active', 450),
  ('Oreo Milkshake', 'Beverages', null, null, 'active', 460),
  ('Butterscotch Milkshake', 'Beverages', null, null, 'active', 470),
  ('Mango Milkshake', 'Beverages', 'Seasonal', null, 'active', 480),
  ('Hot Chocolate', 'Beverages', null, null, 'active', 490),
  ('Tea Powder', 'Ooty Special Products', null, null, 'active', 500),
  ('Eucalyptus Oil', 'Ooty Special Products', null, null, 'active', 510),
  ('Joint Pain Oil', 'Ooty Special Products', null, null, 'active', 520),
  ('Migraine Oil', 'Ooty Special Products', null, null, 'active', 530);
